### ISSUE TITLE
Credible intervals

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dcpo_macrointerest#18]
> R2:  "statistically defensible" sounds like an attempt to talk about statistical significance using non-frequentist language. Perhaps using posterior probabilities instead of credible intervals would be a better option for discussing results.

- [x] Consider using PPC to fit the reviewer's request: https://mc-stan.org/bayesplot/reference/PPC-intervals.html

**Comment by fsolt** [comment]
Just the opposite, I think.  I think he wants us to say something like "98% of the posterior supports the claim."  Need to check out how the lit handles such statements.

**Comment by sammo3182** [comment]
Tried ppc, but required rewriting the model (since the `pp_check` does not recognize `me`. Need using `mi` instead. ref. to https://discourse.mc-stan.org/t/whats-the-difference-between-mi-and-me-in-brms/25883 and https://bookdown.org/content/3890/missing-data-and-other-opportunities.html#bonus-mi-can-replace-me.)
I don't think it is necessary, though, after reading R2's comments again. Just leave the plotting codes in case. I'll remove it in the next push. 

The codes are here: https://github.com/fsolt/dcpo_macrointerest/blob/9be743e01062939f66f46940850fe9b5638b80bd/paper/dcpo_macrointerest.Rmd#L1705-L1780
