### ISSUE TITLE
Replication issues

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dcpo_macrointerest#19]
1. The following line cannot find the files: https://github.com/fsolt/dcpo_macrointerest/blob/6aedb052e20ccd3feb4d3c9d728a574568997a24/paper/dcpo_macrointerest.Rmd#L312-L317
   I downloaded the files from OSF and put them into a folder named "dcpo_surveys." The error still appears.
1. https://github.com/fsolt/dcpo_macrointerest/blob/6aedb052e20ccd3feb4d3c9d728a574568997a24/paper/dcpo_macrointerest.Rmd#L608 The codes given a non-informational error: 

```
curl: (56) Failure when receiving data from the peer

make: *** [make/stanc:91: bin/stanc] Error 56

Error: An error occured during compilation! See the message above for more information.
```
Is this `dcpo.stan` different from the one included in the DCPO package?

**Comment by fsolt** [comment]
As I mentioned in our meeting, this is all eval=FALSE, but (1) of course you'd have to reset datapath to your directory that has all the surveys and (2) it's the same file.
