### ISSUE TITLE
Nonfunctional cache

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dcpo_macrointerest#22]
I set `cache=TRUE` for the chunk `dcpo_summary`. https://github.com/fsolt/dcpo_macrointerest/blob/9be743e01062939f66f46940850fe9b5638b80bd/paper/dcpo_macrointerest.Rmd#L685-L705
However, the compilation is still stuck there for a while every time. 
No idea what leads to that problem.

**Comment by fsolt** [comment]
The issue is that, as far as I can tell, cmdstanr output can only be saved as csv files and reloaded using `as_cmdstan_fit`.  Saving `dcpo_output` as  an .rds and then trying to read that .rds file throws errors, and trying to cache the cmdstan_fit object also throws errors.
