### ISSUE TITLE
Word count

### ISSUE THREAD

**Issue by fsolt** [fsolt/dcpo_macrointerest#23]
Needs to be under 4000 words (excluding abstract)

**Comment by fsolt** [comment]
Currently at 4608 (with abstract)

**Comment by sammo3182** [comment]
One part  may be reducing the explicit discussion of the results to a more 95% confidence + direction description?

https://github.com/fsolt/dcpo_macrointerest/blob/979af0dc254c7fb952881fc9153feb4f7b6715f6/paper/dcpo_macrointerest.Rmd#L1322-L1338

**Comment by fsolt** [comment]
Note to self: don't forget to drop doi links from bib file.  That will help a bit.

**Comment by fsolt** [comment]
I just saw that you noticed (in #8) that the bibliography doesn't count (per ["NOTE: All parts of the manuscript count towards the word count with the exception of the appendix and the bibliography. Please include all word counts in total."](https://www.cambridge.org/core/journals/british-journal-of-political-science/information/author-instructions/preparing-your-materials)).  That helps a _ton_: it puts us currently at 3718, so word count shouldn't be a real problem.

**Comment by sammo3182** [comment]
> I just saw that you noticed (in #8) that the bibliography doesn't count (per ["NOTE: All parts of the manuscript count towards the word count with the exception of the appendix and the bibliography. Please include all word counts in total."](https://www.cambridge.org/core/journals/british-journal-of-political-science/information/author-instructions/preparing-your-materials)). That helps a _ton_: it puts us currently at 3718, so word count shouldn't be a real problem.

We have 4011 now.

**Comment by fsolt** [comment]
Most recently, 4077, including abstract, which, double-checking the journal cite, does count.  I'll trim.

**Comment by fsolt** [comment]
Ugh!  These directions, at submission, do not correspond to the advice for authors.   All that time spend trimming for nothing.  Oh well.
<img width="721" alt="Untitled" src="https://github.com/fsolt/dcpo_macrointerest/assets/6536645/2de9a143-b8ff-49fa-b6d8-303d756f87a2">

I guess it should really be 3850 here, but whatever

**Comment by sammo3182** [comment]
> Ugh! These directions, at submission, do not correspond to the advice for authors. All that time spend trimming for nothing. Oh well. <img alt="Untitled" width="721" src="https://private-user-images.githubusercontent.com/6536645/301586647-2de9a143-b8ff-49fa-b6d8-303d756f87a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4MjU0NjksIm5iZiI6MTcwNjgyNTE2OSwicGF0aCI6Ii82NTM2NjQ1LzMwMTU4NjY0Ny0yZGU5YTE0My1iOGZmLTQ5ZmEtYjZkOC0zMDNkNzU2Zjg3YTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMjIwNjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWMyYTlhOWUyNTQwZTc5YjFkODM4MDA5NGIwZTZkMWQwYTNiNjdjMWUwYzg3Y2YzNDRlMmRiZWI5NzhjOThjZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dhpQyS1MLiB4CgjLXajsbjlvwEUnxPyAqC85eGvPYSI">
> 
> I guess it should really be 3850 here, but whatever

I bet they just used a preset system and were too lazy to modify the narratives, haha~

**Comment by fsolt** [comment]
Quite possible.  Or substitute "not obsessive" for "lazy"

**Comment by fsolt** [comment]
Thanks again for all of your help on this, Hu.  Good luck to us!
