### ISSUE TITLE
Necessity of the within-between model

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dcpo_macrointerest#4]
> R1: Two-Step Approach to Test Hypotheses: Your use of the hierarchical within-between model effectively demonstrates the utility of your approach. However, it may be worth exploring whether this could be achieved in a single step by integrating hierarchical priors into the model. If implementing such a modification is not straightforward, you could discuss it as a potential point of consideration in the conclusion or as a footnote. 

- [ ] Integrate the priors into the model 

OR

- [ ] Discuss the potential to do so in the conclusion

**Comment by sammo3182** [comment]
Fred @fsolt, I need your help with this issue.

**Comment by fsolt** [comment]
This is the "why don't you make one big model like Claassen now advocates" question.  The answer is because that assumes that the country-years missing source data are missing at random, which probably isn't true.  I'll take care of it.
