### ISSUE TITLE
Syntax and framing

### ISSUE THREAD

**Issue by sammo3182** [fsolt/dcpo_macrointerest#8]
> R1: Consider to restructure the introduction into three paragraphs to address the relevance of Macrointerest, the challenges faced by previous research, and the specific contribution and findings of your letter.

> In the sentence mentioning DCPO modeling, there appears to be a copy-paste error with the term "civil servants." Please review and correct as needed.

> Footnote 1 in the appendix is the same as Footnote 2 in the main text. It may be preferable to remove one of them to avoid duplication.

> Consider revising "impressively well in validation tests" to simply "well in validation tests" since the tests'
standards are not explicitly high.

> The meaning of "and so makes a poor choice for cross-national data (see Caughey, O'Grady, and Warshaw 2019,
686)" is unclear. It may be best to remove this sentence, or rewrite it.

> R2: Table A1: abbreviations of names of survey projects are not explained. I was mostly able to make out their
meaning, but not for all (e.g., autnes?)

>  Figure A1 is hard to read and should be split it into two parts.

>  Figure 5 is nice, but I would have liked to see the full regression table too.

> The paper should provide references to all survey datasets used in the analysis, including their versions. This will take many pages, so should probably be put in the appendix, but I think it's important to (a) give credit to the data creators, and (b) document data versions for the readers and potential replicators.

- [x] Break the intro into three paragraphs
- [x] Fix the copy-paste typo
- [x] Fix the footnote in the appendix
- [x] Revise the line https://github.com/fsolt/dcpo_macrointerest/blob/6aedb052e20ccd3feb4d3c9d728a574568997a24/paper/dcpo_macrointerest.Rmd#L303
- [x] Revise or remove the line https://github.com/fsolt/dcpo_macrointerest/blob/6aedb052e20ccd3feb4d3c9d728a574568997a24/paper/dcpo_macrointerest.Rmd#L581C4-L581C4
- [x] Revise table A1 with a full name list
- [x] Split Figure A1 by continent? 
- [x] Alright, alright, regression table in the appendix
- [x] #24

**Comment by sammo3182** [comment]
Fred @fsolt, do you have the record of the full list of source surveys (full name, link, etc.)?

**Comment by fsolt** [comment]
The closest we have to something like that, I think, is https://github.com/fsolt/DCPOtools/blob/master/data/surveys_data.csv

In other words, not really, although the file_id and data_link go some way in that direction.

**Comment by sammo3182** [comment]
Fred @fsolt , what survey do `cispol1989` and `feb162` stand for?

**Comment by fsolt** [comment]
`feb162` is the Flash Eurobarometer 162, https://search.gesis.org/research_data/ZA4186
`cispol1989` is the CIS Cultura Política 1989, https://www.cis.es/detalle-ficha-estudio?origen=estudio&idEstudio=780

**Comment by fsolt** [comment]
- [x] Add info to survey-item and survey tables so they can be cross-referenced (current survey-item table lacks any info about in what survey item was asked)

**Comment by sammo3182** [comment]
> * [ ]  Add info to survey-item and survey tables so they can be cross-referenced (current survey-item table lacks any info about in what survey item was asked)

Fred @fsolt , I thought about that, especially since you included such a column in the first version of the table. When I revised it though, I finally left it out of Table A2, because, first, we did not mention any survey item in the main text (unlike the janitor paper), and second, if we add it we need to match it with surveys in specific waves, which will be an additional super-dense column or another giant table. Do you think the readers want to know which exact item was from which wave of what survey? If they want that detailed data we can give them data file instead of showing it in the appendix, don't we? What do you think?

**Comment by fsolt** [comment]
I think that excluding the items and surveys from Table A1 left it feeling incomplete: it was basically just a list of survey questions with no way of knowing where they were from.  Given that the reviewers wanted more information, cutting from the table seemed the wrong way to go.  It doesn't actually take much space, and it's the appendix anyway.

**Comment by fsolt** [comment]
Closed by 1b9e9d2
